### ISSUE TITLE
Investigate SymPy

### ISSUE THREAD

**Issue by david-istvan** [david-istvan/ICM#52]
Relates to #31 #37 #20 #49

**Comment by david-istvan** [comment]
Also see: https://github.com/yuemingl/SymJava

**Comment by david-istvan** [comment]
- SymJava is not a viable alternative of SymPy, it's only a subset of it. We definitely need SymPy.

- There are limitations when using SymPy from Jython, so we are going to approach via scripts run through the runtime.

**Comment by david-istvan** [comment]
Ridiculous issue: the library doesn't handle doubles well in case of unsatisfiable constraint sets.

```
from __future__ import division
from sympy import *

#Variables and symbols
platformMass = symbols('platformMass')
motorMass = symbols('motorMass')
totalMass = symbols('totalMass')
batteryMass = symbols('batteryMass')
totalMass = symbols('totalMass')

#Equations
eq0 = Le(platformMass+motorMass+batteryMass, totalMass)
eq1 = Le(totalMass, 160)

#Substitutions
eq0 = eq0.subs([(platformMass, 100.0)])
eq0 = eq0.subs([(motorMass, 50.0)])
eq0 = eq0.subs([(batteryMass, 11.0)])

#Solve
print(solve([eq0, eq1]))
```

This would fail with an error: 

```
Traceback (most recent call last):
  File "<pyshell#163>", line 1, in <module>
    print(solve([eq0, eq1]))
  File "C:\Program Files\Python\Python35\lib\site-packages\sympy-1.0-py3.5.egg\sympy\solvers\solvers.py", line 832, in solve
    return reduce_inequalities(f, symbols=symbols)
  File "C:\Program Files\Python\Python35\lib\site-packages\sympy-1.0-py3.5.egg\sympy\solvers\inequalities.py", line 616, in reduce_inequalities
    rv = _reduce_inequalities(inequalities, symbols)
  File "C:\Program Files\Python\Python35\lib\site-packages\sympy-1.0-py3.5.egg\sympy\solvers\inequalities.py", line 554, in _reduce_inequalities
    poly_reduced.append(reduce_rational_inequalities([exprs], gen))
  File "C:\Program Files\Python\Python35\lib\site-packages\sympy-1.0-py3.5.egg\sympy\solvers\inequalities.py", line 265, in reduce_rational_inequalities
    solution = solution.evalf()
AttributeError: 'EmptySet' object has no attribute 'evalf'
```

When using integers, the result is simply "false". When entering doubles (floats, actually) which satisfy the system equations, the result is handled well.

**Comment by david-istvan** [comment]
Conclusion: we opted for using this library via the Runtime instead of Jython.
